# Run the following on your laptop and replace this file with the output:
#   nixos-generate-config --show-hardware-config
#
# Then commit the result here.

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Placeholder — replace with output from nixos-generate-config
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [];

  # fileSystems and swapDevices are generated by disko (hosts/laptop/disko.nix)

  nixpkgs.hostPlatform = "x86_64-linux";
}
